### ISSUE TITLE
ocfweb times out when LDAP is down (so home page is down)

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#103]
when firestorm is down:

```
root@coma:~# time curl -H 'Host: www.ocf.berkeley.edu' http://localhost:8000/
curl: (52) Empty reply from server

real    0m13.193s
user    0m0.008s
sys     0m0.004s
```

however user pages (www.ocf.b.e/~ckuehl) still load due to LDAP caching. not entirely sure what is happening here (I don't think it's actually hitting our Python? not sure)

**Comment by chriskuehl** [comment]
ah, here is a useful log:

```
Dec 18 02:22:37 coma gunicorn[8152]: [2015-12-18 02:22:37 -0800] [13095] [ERROR] Socket error processing request.
Dec 18 02:22:37 coma gunicorn[8152]: Traceback (most recent call last):
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/handlers/base.py", line 134, in get_response
Dec 18 02:22:37 coma gunicorn[8152]: resolver_match = resolver.resolve(request.path_info)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/urlresolvers.py", line 374, in resolve
Dec 18 02:22:37 coma gunicorn[8152]: for pattern in self.url_patterns:
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
Dec 18 02:22:37 coma gunicorn[8152]: res = instance.__dict__[self.name] = self.func(instance)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
Dec 18 02:22:37 coma gunicorn[8152]: patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
Dec 18 02:22:37 coma gunicorn[8152]: res = instance.__dict__[self.name] = self.func(instance)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
Dec 18 02:22:37 coma gunicorn[8152]: return import_module(self.urlconf_name)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/importlib/__init__.py", line 109, in import_module
Dec 18 02:22:37 coma gunicorn[8152]: return _bootstrap._gcd_import(name[level:], package, level)
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 1129, in _exec
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 1471, in exec_module
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/urls.py", line 9, in <module>
Dec 18 02:22:37 coma gunicorn[8152]: from ocfweb.atool.urls import urlpatterns as atool
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/atool/urls.py", line 3, in <module>
Dec 18 02:22:37 coma gunicorn[8152]: from ocfweb.atool.approve.views import account_created
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/atool/approve/views.py", line 9, in <module>
Dec 18 02:22:37 coma gunicorn[8152]: from ocflib.account.creation import encrypt_password
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/account/creation.py", line 507, in <module>
Dec 18 02:22:37 coma gunicorn[8152]: _get_first_available_uid()
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/account/creation.py", line 90, in _get_first_available_uid
Dec 18 02:22:37 coma gunicorn[8152]: with ldap_ocf() as c:
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
Dec 18 02:22:37 coma gunicorn[8152]: return next(self.gen)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/infra/ldap.py", line 29, in ldap_connection
Dec 18 02:22:37 coma gunicorn[8152]: with ldap3.Connection(server) as connection:
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ldap3/core/connection.py", line 406, in __enter__
Dec 18 02:22:37 coma gunicorn[8152]: self.open()
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ldap3/strategy/sync.py", line 55, in open
Dec 18 02:22:37 coma gunicorn[8152]: BaseStrategy.open(self, reset_usage, read_server_info)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ldap3/strategy/base.py", line 132, in open
Dec 18 02:22:37 coma gunicorn[8152]: raise exception_history[0][1](exception_history[0][2])
Dec 18 02:22:37 coma gunicorn[8152]: ldap3.core.exceptions.LDAPSocketOpenError: socket connection error: [Errno 111] Connection refused
Dec 18 02:22:37 coma gunicorn[8152]: During handling of the above exception, another exception occurred:
Dec 18 02:22:37 coma gunicorn[8152]: Traceback (most recent call last):
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 130, in handle
Dec 18 02:22:37 coma gunicorn[8152]: self.handle_request(listener, req, client, addr)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 187, in handle_request
Dec 18 02:22:37 coma gunicorn[8152]: six.reraise(exc_info[0], exc_info[1], exc_info[2])
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/six.py", line 625, in reraise
Dec 18 02:22:37 coma gunicorn[8152]: raise value
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
Dec 18 02:22:37 coma gunicorn[8152]: respiter = self.wsgi(environ, resp.start_response)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
Dec 18 02:22:37 coma gunicorn[8152]: response = self.get_response(request)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/handlers/base.py", line 230, in get_response
Dec 18 02:22:37 coma gunicorn[8152]: response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/handlers/base.py", line 292, in handle_uncaught_exception
Dec 18 02:22:37 coma gunicorn[8152]: if resolver.urlconf_module is None:
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/utils/functional.py", line 33, in __get__
Dec 18 02:22:37 coma gunicorn[8152]: res = instance.__dict__[self.name] = self.func(instance)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
Dec 18 02:22:37 coma gunicorn[8152]: return import_module(self.urlconf_name)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/importlib/__init__.py", line 109, in import_module
Dec 18 02:22:37 coma gunicorn[8152]: return _bootstrap._gcd_import(name[level:], package, level)
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 1129, in _exec
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 1471, in exec_module
Dec 18 02:22:37 coma gunicorn[8152]: File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/urls.py", line 9, in <module>
Dec 18 02:22:37 coma gunicorn[8152]: from ocfweb.atool.urls import urlpatterns as atool
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/atool/urls.py", line 3, in <module>
Dec 18 02:22:37 coma gunicorn[8152]: from ocfweb.atool.approve.views import account_created
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/atool/approve/views.py", line 9, in <module>
Dec 18 02:22:37 coma gunicorn[8152]: from ocflib.account.creation import encrypt_password
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/account/creation.py", line 507, in <module>
Dec 18 02:22:37 coma gunicorn[8152]: _get_first_available_uid()
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/account/creation.py", line 90, in _get_first_available_uid
Dec 18 02:22:37 coma gunicorn[8152]: with ldap_ocf() as c:
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
Dec 18 02:22:37 coma gunicorn[8152]: return next(self.gen)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/infra/ldap.py", line 29, in ldap_connection
Dec 18 02:22:37 coma gunicorn[8152]: with ldap3.Connection(server) as connection:
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ldap3/core/connection.py", line 406, in __enter__
Dec 18 02:22:37 coma gunicorn[8152]: self.open()
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ldap3/strategy/sync.py", line 55, in open
Dec 18 02:22:37 coma gunicorn[8152]: BaseStrategy.open(self, reset_usage, read_server_info)
Dec 18 02:22:37 coma gunicorn[8152]: File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ldap3/strategy/base.py", line 132, in open
Dec 18 02:22:37 coma gunicorn[8152]: raise exception_history[0][1](exception_history[0][2])
Dec 18 02:22:37 coma gunicorn[8152]: ldap3.core.exceptions.LDAPSocketOpenError: socket connection error: [Errno 111] Connection refused
```

it's failing at import time due to @daradib's LDAP caching, which explains why our error-reporting middleware isn't emailing us tracebacks

**Comment by matthew-mcallister** [comment]
Fixed by https://github.com/ocf/ocflib/pull/33.
