### ISSUE TITLE
Still get emails when SNMP returns bad response

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#134]
```
A problem was encountered and reported via ocflib:

An exception occured in an ocfweb periodic function:

Traceback (most recent call last):
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/caching.py", line 56, in cache_lookup_with_fallback
    raise KeyError('Forcing miss as requested.')
KeyError: 'Forcing miss as requested.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/bin/run_periodic_functions.py", line 47, in run_periodic_functions
    pf.update()
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/caching.py", line 214, in update
    force_miss=True,
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/caching.py", line 66, in cache_lookup_with_fallback
    result = fallback()
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/caching.py", line 170, in function_with_timestamp
    return (datetime.now(), self.function())
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/stats/summary.py", line 81, in printers
    for printer in PRINTERS
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/stats/summary.py", line 81, in <genexpr>
    for printer in PRINTERS
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/stats/summary.py", line 73, in inner
    return f(*args, **kwargs)
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/lab/printing.py", line 48, in get_maintkit
    for oid in (OID_MAINTKIT_CUR, OID_MAINTKIT_MAX)
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/lab/printing.py", line 48, in <genexpr>
    for oid in (OID_MAINTKIT_CUR, OID_MAINTKIT_MAX)
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/pyasn1/type/univ.py", line 476, in __int__
    def __int__(self): return int(self._value)
ValueError: invalid literal for int() with base 10: b''


Periodic function:
  * Key: ('2016.01.31.20.58-git62112ffb', 'ocfweb.stats.summary#printers', (), ())
  * Last Update: 2016-02-01 13:08:26.532276 (71.241317 seconds ago)


  * Period: 60
  * TTL: 120

The background process will now pause for 30 seconds.


====
Hostname: coma.ocf.berkeley.edu
Callstack:
    at /usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/misc/mail.py:59 (send_problem_report)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/bin/run_periodic_functions.py:73 (run_periodic_functions)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/bin/run_periodic_functions.py:116 (main)
        by /usr/share/python/ocfweb/bin/ocfweb-run-periodic-functions:9 (<module>)
```

**Comment by chriskuehl** [comment]
I think this is fixed, we haven't seen these in ages.
