### ISSUE TITLE
Don't 500 when lab_status.yaml or staff_hours.yaml missing

### ISSUE THREAD

**Issue by matthew-mcallister** [ocf/ocfweb#143]
Instead we can just assume lab is open, no banner, and no staff hours.

**Comment by chriskuehl** [comment]
the only concern is that we should probably be notified somehow otherwise we might not know to fix it.

but yeah, i'd like to receive less of those emails when death is down :p

**Comment by matthew-mcallister** [comment]
Should be remedied in https://github.com/ocf/ocfweb/commit/05c00c27369b68576078818a1efd1541ce3f40e2.

**Comment by jvperrin** [comment]
This doesn't appear to be entirely fixed when death is unreachable, given the number of emails sent out this morning:

    A problem was encountered and reported via ocflib:
    
    An exception occured in ocfweb:
    
    Traceback (most recent call last):
      File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/caching.py", line 58, in cache_lookup_with_fallback
        result = cache_lookup(key)
      File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/caching.py", line 31, in cache_lookup
        raise KeyError('Key "{}" is not in the cache.'.format(key))
    KeyError: 'Key "(\'2016.02.16.00.17-gitbd63abba\', \'ocfweb.main.home#get_staff_hours\', (), ())" is not in the cache.'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/main/home.py", line 30, in home
        'staff_hours': get_staff_hours(),
      File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/caching.py", line 204, in result
        ttl=self.ttl,
      File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/caching.py", line 66, in cache_lookup_with_fallback
        result = fallback()
      File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/caching.py", line 170, in function_with_timestamp
        return (datetime.now(), self.function())
      File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/main/home.py", line 15, in get_staff_hours
        return get_staff_hours_soonest_first()[:2]
      File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/lab/staff_hours.py", line 77, in get_staff_hours_soonest_first
        return sorted(get_staff_hours(), key=lambda hour: days.index(hour.day))
      File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/lab/staff_hours.py", line 65, in get_staff_hours
        ) for hour in staff_hours['staff-hours']
    TypeError: string indices must be integers

**Comment by chriskuehl** [comment]
believe this is now fixed after #157
