### ISSUE TITLE
LDAP query fails when real name contains parentheses

### ISSUE THREAD

**Issue by fydai** [ocf/ocfweb#541]
A problem was encountered and reported via ocflib:

An exception occured in ocfweb:

```
Traceback (most recent call last):
  File "/opt/ocfweb/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ocfweb/ocfweb/account/register.py", line 122, in recommend
    recommendations = recommender.recommend(real_name, 10)
  File "/opt/ocfweb/ocfweb/account/recommender.py", line 30, in recommend
    validate_username(rec, real_name)
  File "/opt/ocfweb/venv/lib/python3.7/site-packages/ocflib/account/creation.py", line 345, in validate_username
    if search.user_exists(username):
  File "/opt/ocfweb/venv/lib/python3.7/site-packages/ocflib/account/search.py", line 61, in user_exists
    return bool(user_attrs(account))
  File "/opt/ocfweb/venv/lib/python3.7/site-packages/ocflib/account/search.py", line 48, in user_attrs
    c.search(base, '(uid={})'.format(uid), attributes=ldap3.ALL_ATTRIBUTES)
  File "/opt/ocfweb/venv/lib/python3.7/site-packages/ldap3/core/connection.py", line 785, in search
    check_names=self.check_names)
  File "/opt/ocfweb/venv/lib/python3.7/site-packages/ldap3/operation/search.py", line 372, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node
  File "/opt/ocfweb/venv/lib/python3.7/site-packages/ldap3/operation/search.py", line 215, in parse_filter
    raise LDAPInvalidFilterError('malformed filter')
ldap3.core.exceptions.LDAPInvalidFilterError: malformed filter
```

Request:
  * Host: www.ocf.berkeley.edu
  * Path: /account/register/recommend/?real_name=<redacted name with parens>
  * Method: GET
  * Secure: True

**Comment by dkess** [comment]
This is the same as https://github.com/ocf/ocflib/issues/150

**Comment by ethanhs** [comment]
Closing as duplicate.
