### ISSUE TITLE
get_blog_posts sometimes returns None which isn't handled properly

### ISSUE THREAD

**Issue by chriskuehl** [ocf/ocfweb#99]
didn't investigate at all yet

```
A problem was encountered and reported via ocflib:

An exception occured in ocfweb:

Traceback (most recent call last):
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/main/home.py", line 24, in home
    blog_posts = get_blog_posts()[:2]
TypeError: 'NoneType' object is not subscriptable



Request:
  * Host: www.ocf.berkeley.edu
  * Path: /
  * Method: GET
  * Secure: True

Request Headers:
{'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': 'www.ocf.berkeley.edu',
 'HTTP_USER_AGENT': 'Rackspace Monitoring/1.1 '
                    '(https://monitoring.api.rackspacecloud.com)',
 'HTTP_X_FORWARDED_FOR': '78.136.44.23, 169.229.226.23',
 'HTTP_X_FORWARDED_HOST': 'www.ocf.berkeley.edu',
 'HTTP_X_FORWARDED_PROTO': 'https',
 'HTTP_X_FORWARDED_SERVER': 'www.ocf.berkeley.edu',
 'PATH_INFO': '/',
 'QUERY_STRING': '',
 'RAW_URI': '/',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '46784',
 'REQUEST_METHOD': 'GET',
 'SCRIPT_NAME': '',
 'SERVER_NAME': '127.0.0.1',
 'SERVER_PORT': '8000',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SOFTWARE': 'gunicorn/19.4.1',
 'gunicorn.socket': <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8000), raddr=('127.0.0.1', 46784)>,
 'wsgi.errors': <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7efe33be1908>,
 'wsgi.file_wrapper': <class 'gunicorn.http.wsgi.FileWrapper'>,
 'wsgi.input': <gunicorn.http.body.Body object at 0x7efe33be1208>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'https',
 'wsgi.version': (1, 0)}

Session:
{}


====
Hostname: coma.ocf.berkeley.edu
Callstack:
    at /usr/share/python/ocfweb/lib/python3.4/site-packages/ocflib/misc/mail.py:59 (send_problem_report)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/ocfweb/middleware/errors.py:47 (process_exception)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/handlers/base.py:262 (process_exception_by_middleware)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/handlers/base.py:149 (get_response)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/django/core/handlers/wsgi.py:177 (__call__)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/workers/sync.py:171 (handle_request)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/workers/sync.py:130 (handle)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/workers/sync.py:30 (accept)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/workers/sync.py:66 (run_for_one)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/workers/sync.py:119 (run)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/workers/base.py:126 (init_process)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/arbiter.py:515 (spawn_worker)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/arbiter.py:548 (spawn_workers)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/arbiter.py:482 (manage_workers)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/arbiter.py:179 (run)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/app/base.py:72 (run)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/app/base.py:192 (run)
        by /usr/share/python/ocfweb/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py:74 (run)
        by /usr/share/python/ocfweb/bin/gunicorn:11 (<module>)
```

**Comment by chriskuehl** [comment]
this is hopefully fixed by #100
